{{- if .Values.shadok.enabled }}
apiVersion: shadok.org/v1
kind: Application
metadata:
  name: {{ include "node-hello.fullname" . }}
spec:
  applicationType: {{ .Values.shadok.application.type }}
  projectSourceName: {{ include "node-hello.fullname" . }}
  dependencyCacheName: {{ include "node-hello.fullname" . }}
---
apiVersion: shadok.org/v1
kind: ProjectSource
metadata:
  name: {{ include "node-hello.fullname" . }}
spec:
  persistentVolumeName: {{ .Values.shadok.sources.pvName }}
  sourcePath: {{ .Values.shadok.sources.path }}
  pvcName: {{ .Values.shadok.sources.pvcName }}
  storageClass: {{ .Values.shadok.sources.storageClass }}
  storageSize: {{ .Values.shadok.sources.storageSize }}
  accessMode: {{ .Values.shadok.sources.accessMode }}
---
apiVersion: shadok.org/v1
kind: DependencyCache
metadata:
  name: {{ include "node-hello.fullname" . }}
spec:
  persistentVolumeName: {{ .Values.shadok.cache.pvName }}
  cachePath: {{ .Values.shadok.cache.path }}
  pvcName: {{ .Values.shadok.cache.pvcName }}
  storageClass: {{ .Values.shadok.cache.storageClass }}
  storageSize: {{ .Values.shadok.cache.storageSize }}
  accessMode: {{ .Values.shadok.cache.accessMode }}
---
{{- end }}

