apiVersion: shadok.org/v1
kind: Application
metadata:
  name: test-app
  namespace: shadok
spec:
  applicationType: QUARKUS_GRADLE
  projectSourceName: "test-project"
  dependencyCacheName: "test-cache"
  initContainerMounts: []
  labels:
    app: "test-application"
    version: "1.0"
