

quarkus.http.port=8080
quarkus.http.ssl-port=8443

# Enable the HTTP management interface
quarkus.management.enabled=true
quarkus.management.port=9000

# TLS configuration named "https"
quarkus.tls.https.key-store.pem.0.cert=/tls/tls.crt
quarkus.tls.https.key-store.pem.0.key=/tls/tls.key
quarkus.http.tls-configuration-name=https

# Webhook configuration
quarkus.kubernetes-client.namespace=shadok
quarkus.kubernetes-client.devservices.enabled=true
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.generate-rbac=true

# Operator SDK configuration
quarkus.operator-sdk.crd.versions=v1
quarkus.operator-sdk.crd.validate=false
quarkus.operator-sdk.enable-ssa=true
quarkus.operator-sdk.generation-aware=false

# Logging configuration
quarkus.log.level=WARN
quarkus.log.category."org.shadok.operator".level=INFO
quarkus.log.category."io.javaoperatorsdk".level=INFO

# Debug profile configuration
%debug.quarkus.log.level=DEBUG
%debug.quarkus.log.category."org.shadok.operator.webhook".level=DEBUG
%debug.quarkus.log.category."io.javaoperatorsdk.operator".level=DEBUG
%debug.quarkus.http.port=8080
%debug.quarkus.http.test-port=8081
