apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: shadok-pod-mutator
webhooks:
  - name: pod-mutator.shadok.org
    clientConfig:
      service:
        name: operator
        namespace: shadok
        path: "/mutate-pods"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Ignore
