apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: shadok-deployment-webhook
webhooks:
  - name: deployment-webhook.shadok.org
    clientConfig:
      service:
        name: shadok-webhook
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public"]
---
apiVersion: v1
kind: Service
metadata:
  name: shadok-webhook
  namespace: default
spec:
  selector:
    app: shadok
  ports:
    - port: 443
      targetPort: 8443
  type: ClusterIP