apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: node-hello
  namespace: default

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

labels:
  - pairs:
      app.kubernetes.io/name: node-hello
      app.kubernetes.io/part-of: shadok-pods
      app.kubernetes.io/managed-by: shadok

namePrefix: ""
nameSuffix: ""

images:
  - name: shadok-pods/node-hello
    newTag: latest

replicas:
  - name: node-hello
    count: 1
