apiVersion: shadok.org/v1
kind: Application
metadata:
  name: quarkus-hello-app
  namespace: shadok
spec:
  applicationType: QUARKUS_GRADLE
  projectSourceName: quarkus-hello-source
  dependencyCacheName: java-cache
---
apiVersion: shadok.org/v1
kind: ProjectSource
metadata:
  name: quarkus-hello-source
  namespace: shadok
spec:
  persistentVolumeName: pv-quarkus-hello-sources
  sourcePath: /
  pvcName: pvc-quarkus-hello-sources
  storageClass: local-storage
  storageSize: 1Gi
  accessMode: ReadOnlyMany
---
apiVersion: shadok.org/v1
kind: DependencyCache
metadata:
  name: java-cache
  namespace: shadok
spec:
  persistentVolumeName: pv-java-cache
  cachePath: /cache
  pvcName: java-cache-pvc
  storageClass: local-storage
  storageSize: 10Gi
  accessMode: ReadWriteMany
---
apiVersion: shadok.org/v1
kind: Application
metadata:
  name: test-app
  namespace: shadok
spec:
  applicationType: QUARKUS_GRADLE
  projectSourceName: "quarkus-hello-source"
  dependencyCacheName: "java-cache"
  initContainerMounts: []
  labels:
    app: "test-application"
    version: "1.0"
