apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "operator.fullname" .) .Values.service.name }}
  labels:
    {{ include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{ include "operator.selectorLabels" . | nindent 4 }}
