{{- if .Values.webhook.create }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ default (include "operator.fullname" .) .Values.webhook.configuration.name }}
  annotations:
    {{- if .Values.webhook.certificate.create }}
    cert-manager.io/inject-ca-from: shadok/webhook-server-cert
    {{- end }}
    {{- if .Values.webhook.configuration.annotations }}
    {{ toYaml .Values.webhook.configuration.annotations | nindent 4 }}
    {{- end }}
webhooks:
  - name: pod-mutator.shadok.org
    clientConfig:
      service:
        name: {{ default (include "operator.fullname" .) .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate-pods"
        port: {{ .Values.service.port }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    namespaceSelector: {}
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - {{ include "operator.name" . }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
{{- end }}