apiVersion: v1
kind: Service
metadata:
  name: python-hello
  namespace: default
  labels:
    app.kubernetes.io/name: python-hello
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: shadok-pods
    app.kubernetes.io/managed-by: shadok
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: python-hello
